/*
 * Stationsdatenbereitstellung
 * An API providing master data for german railway stations by DB Station&Service AG.
 *
 * OpenAPI spec version: 2.2.01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.github.martintaraz.hackathon2018.models.stations;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Error
 */
@javax.annotation.processing.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-07T20:50:44.823+01:00")
public class Error {
  @SerializedName("errNo")
  private Integer errNo = null;

  @SerializedName("errMsg")
  private String errMsg = null;

  public Error errNo(Integer errNo) {
    this.errNo = errNo;
    return this;
  }

   /**
   * error number
   * @return errNo
  **/
  @ApiModelProperty(value = "error number")
  public Integer getErrNo() {
    return errNo;
  }

  public void setErrNo(Integer errNo) {
    this.errNo = errNo;
  }

  public Error errMsg(String errMsg) {
    this.errMsg = errMsg;
    return this;
  }

   /**
   * error message
   * @return errMsg
  **/
  @ApiModelProperty(value = "error message")
  public String getErrMsg() {
    return errMsg;
  }

  public void setErrMsg(String errMsg) {
    this.errMsg = errMsg;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Error error = (Error) o;
    return Objects.equals(this.errNo, error.errNo) &&
        Objects.equals(this.errMsg, error.errMsg);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errNo, errMsg);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Error {\n");
    
    sb.append("    errNo: ").append(toIndentedString(errNo)).append("\n");
    sb.append("    errMsg: ").append(toIndentedString(errMsg)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

