/*
 * Stationsdatenbereitstellung
 * An API providing master data for german railway stations by DB Station&Service AG.
 *
 * OpenAPI spec version: 2.2.01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.github.martintaraz.hackathon2018.models.stations;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * GEOJSON object of type point. By default WGS84 is the coordinate system in GEOJSON.
 */
@ApiModel(description = "GEOJSON object of type point. By default WGS84 is the coordinate system in GEOJSON.")
@javax.annotation.processing.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-07T20:50:44.823+01:00")
public class GeographicPoint {
  @SerializedName("type")
  private String type = null;

  @SerializedName("coordinates")
  private List<Double> coordinates = null;

  public GeographicPoint type(String type) {
    this.type = type;
    return this;
  }

   /**
   * the type of the GEOJSON Object e.g. point. Currently only point coordinates without altitude are provided.
   * @return type
  **/
  @ApiModelProperty(value = "the type of the GEOJSON Object e.g. point. Currently only point coordinates without altitude are provided.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public GeographicPoint coordinates(List<Double> coordinates) {
    this.coordinates = coordinates;
    return this;
  }

  public GeographicPoint addCoordinatesItem(Double coordinatesItem) {
    if (this.coordinates == null) {
      this.coordinates = new ArrayList<Double>();
    }
    this.coordinates.add(coordinatesItem);
    return this;
  }

   /**
   * first value is longitude, second latitude third altitude (currently not provided)
   * @return coordinates
  **/
  @ApiModelProperty(value = "first value is longitude, second latitude third altitude (currently not provided)")
  public List<Double> getCoordinates() {
    return coordinates;
  }

  public void setCoordinates(List<Double> coordinates) {
    this.coordinates = coordinates;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeographicPoint geographicPoint = (GeographicPoint) o;
    return Objects.equals(this.type, geographicPoint.type) &&
        Objects.equals(this.coordinates, geographicPoint.coordinates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, coordinates);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeographicPoint {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    coordinates: ").append(toIndentedString(coordinates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

