/*
 * Stationsdatenbereitstellung
 * An API providing master data for german railway stations by DB Station&Service AG.
 *
 * OpenAPI spec version: 2.2.01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.github.martintaraz.hackathon2018.models.stations;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;

/**
 * period of time from/to
 */
@ApiModel(description = "period of time from/to")
@javax.annotation.processing.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-07T20:50:44.823+01:00")
public class OpeningHours {
  @SerializedName("fromTime")
  private LocalDate fromTime = null;

  @SerializedName("toTime")
  private LocalDate toTime = null;

  public OpeningHours fromTime(LocalDate fromTime) {
    this.fromTime = fromTime;
    return this;
  }

   /**
   * Get fromTime
   * @return fromTime
  **/
  @ApiModelProperty(value = "")
  public LocalDate getFromTime() {
    return fromTime;
  }

  public void setFromTime(LocalDate fromTime) {
    this.fromTime = fromTime;
  }

  public OpeningHours toTime(LocalDate toTime) {
    this.toTime = toTime;
    return this;
  }

   /**
   * Get toTime
   * @return toTime
  **/
  @ApiModelProperty(value = "")
  public LocalDate getToTime() {
    return toTime;
  }

  public void setToTime(LocalDate toTime) {
    this.toTime = toTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpeningHours openingHours = (OpeningHours) o;
    return Objects.equals(this.fromTime, openingHours.fromTime) &&
        Objects.equals(this.toTime, openingHours.toTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fromTime, toTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpeningHours {\n");
    
    sb.append("    fromTime: ").append(toIndentedString(fromTime)).append("\n");
    sb.append("    toTime: ").append(toIndentedString(toTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

