/*
 * Stationsdatenbereitstellung
 * An API providing master data for german railway stations by DB Station&Service AG.
 *
 * OpenAPI spec version: 2.2.01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.github.martintaraz.hackathon2018.models.stations;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * reference object contained in station
 */
@ApiModel(description = "reference object contained in station")
@javax.annotation.processing.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-07T20:50:44.823+01:00")
public class SZentraleRef {
  @SerializedName("number")
  private Integer number = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("publicPhoneNumber")
  private String publicPhoneNumber = null;

  public SZentraleRef number(Integer number) {
    this.number = number;
    return this;
  }

   /**
   * unique identifier for SZentrale
   * @return number
  **/
  @ApiModelProperty(value = "unique identifier for SZentrale")
  public Integer getNumber() {
    return number;
  }

  public void setNumber(Integer number) {
    this.number = number;
  }

  public SZentraleRef name(String name) {
    this.name = name;
    return this;
  }

   /**
   * unique identifier of 3SZentrale
   * @return name
  **/
  @ApiModelProperty(value = "unique identifier of 3SZentrale")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SZentraleRef publicPhoneNumber(String publicPhoneNumber) {
    this.publicPhoneNumber = publicPhoneNumber;
    return this;
  }

   /**
   * Get publicPhoneNumber
   * @return publicPhoneNumber
  **/
  @ApiModelProperty(value = "")
  public String getPublicPhoneNumber() {
    return publicPhoneNumber;
  }

  public void setPublicPhoneNumber(String publicPhoneNumber) {
    this.publicPhoneNumber = publicPhoneNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SZentraleRef szentraleRef = (SZentraleRef) o;
    return Objects.equals(this.number, szentraleRef.number) &&
        Objects.equals(this.name, szentraleRef.name) &&
        Objects.equals(this.publicPhoneNumber, szentraleRef.publicPhoneNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(number, name, publicPhoneNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SZentraleRef {\n");
    
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    publicPhoneNumber: ").append(toIndentedString(publicPhoneNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

