/*
 * Stationsdatenbereitstellung
 * An API providing master data for german railway stations by DB Station&Service AG.
 *
 * OpenAPI spec version: 2.2.01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.github.martintaraz.dbdatapublisherbot.models.stations;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * local public sector entity, responsible for short distance public transport in a specific area
 */
@ApiModel(description = "local public sector entity, responsible for short distance public transport in a specific area")
@javax.annotation.processing.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-07T20:50:44.823+01:00")
public class Aufgabentraeger {
  @SerializedName("shortname")
  private String shortname = null;

  @SerializedName("name")
  private String name = null;

  public Aufgabentraeger shortname(String shortname) {
    this.shortname = shortname;
    return this;
  }

   /**
   * unique identifier
   * @return shortname
  **/
  @ApiModelProperty(value = "unique identifier")
  public String getShortname() {
    return shortname;
  }

  public void setShortname(String shortname) {
    this.shortname = shortname;
  }

  public Aufgabentraeger name(String name) {
    this.name = name;
    return this;
  }

   /**
   * full name of Aufgabentraeger
   * @return name
  **/
  @ApiModelProperty(value = "full name of Aufgabentraeger")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Aufgabentraeger aufgabentraeger = (Aufgabentraeger) o;
    return Objects.equals(this.shortname, aufgabentraeger.shortname) &&
        Objects.equals(this.name, aufgabentraeger.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shortname, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Aufgabentraeger {\n");
    
    sb.append("    shortname: ").append(toIndentedString(shortname)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

