/*
 * Stationsdatenbereitstellung
 * An API providing master data for german railway stations by DB Station&Service AG.
 *
 * OpenAPI spec version: 2.2.01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.github.martintaraz.dbdatapublisherbot.models.stations;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.github.martintaraz.dbdatapublisherbot.models.stations.GeographicPoint;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;

/**
 * EVANumber
 */
@javax.annotation.processing.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-07T20:50:44.823+01:00")
public class EVANumber {
  @SerializedName("number")
  private Integer number = null;

  @SerializedName("isMain")
  private Boolean isMain = null;

  @SerializedName("geographicCoordinates")
  private GeographicPoint geographicCoordinates = null;

  public EVANumber number(Integer number) {
    this.number = number;
    return this;
  }

   /**
   * EVA identifier
   * @return number
  **/
  @ApiModelProperty(value = "EVA identifier")
  public Integer getNumber() {
    return number;
  }

  public void setNumber(Integer number) {
    this.number = number;
  }

  public EVANumber isMain(Boolean isMain) {
    this.isMain = isMain;
    return this;
  }

   /**
   * station related EVA-Numbers
   * @return isMain
  **/
  @ApiModelProperty(value = "station related EVA-Numbers")
  public Boolean isIsMain() {
    return isMain;
  }

  public void setIsMain(Boolean isMain) {
    this.isMain = isMain;
  }

  public EVANumber geographicCoordinate(GeographicPoint geographicCoordinate) {
    this.geographicCoordinates = geographicCoordinate;
    return this;
  }

   /**
   * Get geographicCoordinates
   * @return geographicCoordinates
  **/
  @ApiModelProperty(value = "")
  public GeographicPoint getGeographicCoordinates() {
    return geographicCoordinates;
  }

  public void setGeographicCoordinates(GeographicPoint geographicCoordinate) {
    this.geographicCoordinates = geographicCoordinate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EVANumber evANumber = (EVANumber) o;
    return Objects.equals(this.number, evANumber.number) &&
        Objects.equals(this.isMain, evANumber.isMain) &&
        Objects.equals(this.geographicCoordinates, evANumber.geographicCoordinates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(number, isMain, geographicCoordinates);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EVANumber {\n");
    
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    isMain: ").append(toIndentedString(isMain)).append("\n");
    sb.append("    geographicCoordinates: ").append(toIndentedString(geographicCoordinates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

