/*
 * Stationsdatenbereitstellung
 * An API providing master data for german railway stations by DB Station&Service AG.
 *
 * OpenAPI spec version: 2.2.01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.github.martintaraz.dbdatapublisherbot.models.stations;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets Partial
 */
@JsonAdapter(Partial.Adapter.class)
public enum Partial {
  
  YES("yes"),
  
  NO("no"),
  
  PARTIAL("partial");

  private String value;

  Partial(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Partial fromValue(String text) {
    for (Partial b : Partial.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<Partial> {
    @Override
    public void write(final JsonWriter jsonWriter, final Partial enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public Partial read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return Partial.fromValue(String.valueOf(value));
    }
  }
}

