/*
 * Stationsdatenbereitstellung
 * An API providing master data for german railway stations by DB Station&Service AG.
 *
 * OpenAPI spec version: 2.2.01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.github.martintaraz.dbdatapublisherbot.models.stations;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.github.martintaraz.dbdatapublisherbot.models.stations.OpeningHours;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;

/**
 * a weekly schedule
 */
@ApiModel(description = "a weekly schedule")
@javax.annotation.processing.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-07T20:50:44.823+01:00")
public class Schedule {
  @SerializedName("monday")
  private OpeningHours monday = null;

  @SerializedName("tuesday")
  private OpeningHours tuesday = null;

  @SerializedName("wednesday")
  private OpeningHours wednesday = null;

  @SerializedName("thursday")
  private OpeningHours thursday = null;

  @SerializedName("friday")
  private OpeningHours friday = null;

  @SerializedName("saturday")
  private OpeningHours saturday = null;

  @SerializedName("sunday")
  private OpeningHours sunday = null;

  @SerializedName("holiday")
  private OpeningHours holiday = null;

  public Schedule monday(OpeningHours monday) {
    this.monday = monday;
    return this;
  }

   /**
   * Get monday
   * @return monday
  **/
  @ApiModelProperty(value = "")
  public OpeningHours getMonday() {
    return monday;
  }

  public void setMonday(OpeningHours monday) {
    this.monday = monday;
  }

  public Schedule tuesday(OpeningHours tuesday) {
    this.tuesday = tuesday;
    return this;
  }

   /**
   * Get tuesday
   * @return tuesday
  **/
  @ApiModelProperty(value = "")
  public OpeningHours getTuesday() {
    return tuesday;
  }

  public void setTuesday(OpeningHours tuesday) {
    this.tuesday = tuesday;
  }

  public Schedule wednesday(OpeningHours wednesday) {
    this.wednesday = wednesday;
    return this;
  }

   /**
   * Get wednesday
   * @return wednesday
  **/
  @ApiModelProperty(value = "")
  public OpeningHours getWednesday() {
    return wednesday;
  }

  public void setWednesday(OpeningHours wednesday) {
    this.wednesday = wednesday;
  }

  public Schedule thursday(OpeningHours thursday) {
    this.thursday = thursday;
    return this;
  }

   /**
   * Get thursday
   * @return thursday
  **/
  @ApiModelProperty(value = "")
  public OpeningHours getThursday() {
    return thursday;
  }

  public void setThursday(OpeningHours thursday) {
    this.thursday = thursday;
  }

  public Schedule friday(OpeningHours friday) {
    this.friday = friday;
    return this;
  }

   /**
   * Get friday
   * @return friday
  **/
  @ApiModelProperty(value = "")
  public OpeningHours getFriday() {
    return friday;
  }

  public void setFriday(OpeningHours friday) {
    this.friday = friday;
  }

  public Schedule saturday(OpeningHours saturday) {
    this.saturday = saturday;
    return this;
  }

   /**
   * Get saturday
   * @return saturday
  **/
  @ApiModelProperty(value = "")
  public OpeningHours getSaturday() {
    return saturday;
  }

  public void setSaturday(OpeningHours saturday) {
    this.saturday = saturday;
  }

  public Schedule sunday(OpeningHours sunday) {
    this.sunday = sunday;
    return this;
  }

   /**
   * Get sunday
   * @return sunday
  **/
  @ApiModelProperty(value = "")
  public OpeningHours getSunday() {
    return sunday;
  }

  public void setSunday(OpeningHours sunday) {
    this.sunday = sunday;
  }

  public Schedule holiday(OpeningHours holiday) {
    this.holiday = holiday;
    return this;
  }

   /**
   * Get holiday
   * @return holiday
  **/
  @ApiModelProperty(value = "")
  public OpeningHours getHoliday() {
    return holiday;
  }

  public void setHoliday(OpeningHours holiday) {
    this.holiday = holiday;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Schedule schedule = (Schedule) o;
    return Objects.equals(this.monday, schedule.monday) &&
        Objects.equals(this.tuesday, schedule.tuesday) &&
        Objects.equals(this.wednesday, schedule.wednesday) &&
        Objects.equals(this.thursday, schedule.thursday) &&
        Objects.equals(this.friday, schedule.friday) &&
        Objects.equals(this.saturday, schedule.saturday) &&
        Objects.equals(this.sunday, schedule.sunday) &&
        Objects.equals(this.holiday, schedule.holiday);
  }

  @Override
  public int hashCode() {
    return Objects.hash(monday, tuesday, wednesday, thursday, friday, saturday, sunday, holiday);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Schedule {\n");
    
    sb.append("    monday: ").append(toIndentedString(monday)).append("\n");
    sb.append("    tuesday: ").append(toIndentedString(tuesday)).append("\n");
    sb.append("    wednesday: ").append(toIndentedString(wednesday)).append("\n");
    sb.append("    thursday: ").append(toIndentedString(thursday)).append("\n");
    sb.append("    friday: ").append(toIndentedString(friday)).append("\n");
    sb.append("    saturday: ").append(toIndentedString(saturday)).append("\n");
    sb.append("    sunday: ").append(toIndentedString(sunday)).append("\n");
    sb.append("    holiday: ").append(toIndentedString(holiday)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

