/*
 * Stationsdatenbereitstellung
 * An API providing master data for german railway stations by DB Station&Service AG.
 *
 * OpenAPI spec version: 2.2.01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.github.martintaraz.dbdatapublisherbot.models.stations;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.github.martintaraz.dbdatapublisherbot.models.stations.Address;
import io.github.martintaraz.dbdatapublisherbot.models.stations.Aufgabentraeger;
import io.github.martintaraz.dbdatapublisherbot.models.stations.EVANumber;
import io.github.martintaraz.dbdatapublisherbot.models.stations.Partial;
import io.github.martintaraz.dbdatapublisherbot.models.stations.RegionalBereichRef;
import io.github.martintaraz.dbdatapublisherbot.models.stations.RiL100Identifier;
import io.github.martintaraz.dbdatapublisherbot.models.stations.SZentraleRef;
import io.github.martintaraz.dbdatapublisherbot.models.stations.Schedule;
import io.github.martintaraz.dbdatapublisherbot.models.stations.StationManagementRef;
import io.github.martintaraz.dbdatapublisherbot.models.stations.TimetableOffice;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Station
 */
@javax.annotation.processing.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-07T20:50:44.823+01:00")
public class Station {
  @SerializedName("number")
  private Integer number = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("mailingAddress")
  private Address mailingAddress = null;

  @SerializedName("category")
  private Integer category = null;

  @SerializedName("priceCategory")
  private Integer priceCategory = null;

  @SerializedName("federalState")
  private String federalState = null;

  @SerializedName("hasParking")
  private Boolean hasParking = null;

  @SerializedName("hasBicycleParking")
  private Boolean hasBicycleParking = null;

  @SerializedName("hasPublicFacilities")
  private Boolean hasPublicFacilities = null;

  @SerializedName("hasLockerSystem")
  private Boolean hasLockerSystem = null;

  @SerializedName("hasLocalPublicTransport")
  private Boolean hasLocalPublicTransport = null;

  @SerializedName("hasTaxiRank")
  private Boolean hasTaxiRank = null;

  @SerializedName("hasTravelNecessities")
  private Boolean hasTravelNecessities = null;

  @SerializedName("hasSteplessAccess")
  private Partial hasSteplessAccess = null;

  @SerializedName("hasMobilityService")
  private String hasMobilityService = null;

  @SerializedName("hasWiFi")
  private Boolean hasWiFi = null;

  @SerializedName("hasTravelCenter")
  private Boolean hasTravelCenter = null;

  @SerializedName("hasRailwayMission")
  private Boolean hasRailwayMission = null;

  @SerializedName("hasDBLounge")
  private Boolean hasDBLounge = null;

  @SerializedName("hasLostAndFound")
  private Boolean hasLostAndFound = null;

  @SerializedName("hasCarRental")
  private Boolean hasCarRental = null;

  @SerializedName("evaNumbers")
  private List<EVANumber> evaNumbers = null;

  @SerializedName("ril100Identifiers")
  private List<RiL100Identifier> ril100Identifiers = null;

  @SerializedName("timetableOffice")
  private TimetableOffice timetableOffice = null;

  @SerializedName("stationManagement")
  private StationManagementRef stationManagement = null;

  @SerializedName("localServiceStaff")
  private Schedule localServiceStaff = null;

  @SerializedName("DBinformation")
  private Schedule dbinformation = null;

  @SerializedName("regionalbereich")
  private RegionalBereichRef regionalbereich = null;

  @SerializedName("szentrale")
  private SZentraleRef szentrale = null;

  @SerializedName("aufgabentraeger")
  private Aufgabentraeger aufgabentraeger = null;

  public Station number(Integer number) {
    this.number = number;
    return this;
  }

   /**
   * unique identifier representing a specific railway station
   * @return number
  **/
  @ApiModelProperty(value = "unique identifier representing a specific railway station")
  public Integer getNumber() {
    return number;
  }

  public void setNumber(Integer number) {
    this.number = number;
  }

  public Station name(String name) {
    this.name = name;
    return this;
  }

   /**
   * the stations name
   * @return name
  **/
  @ApiModelProperty(value = "the stations name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Station mailingAdress(Address mailingAdress) {
    this.mailingAddress = mailingAdress;
    return this;
  }

   /**
   * mailing address of the railway station
   * @return mailingAddress
  **/
  @ApiModelProperty(value = "mailing address of the railway station")
  public Address getMailingAddress() {
    return mailingAddress;
  }

  public void setMailingAddress(Address mailingAdress) {
    this.mailingAddress = mailingAdress;
  }

  public Station category(Integer category) {
    this.category = category;
    return this;
  }

   /**
   * the stations category (-1...7). Stations with category -1 or 0 are not in production, e.g. planned, saled, without train stops.
   * @return category
  **/
  @ApiModelProperty(value = "the stations category (-1...7). Stations with category -1 or 0 are not in production, e.g. planned, saled, without train stops.")
  public Integer getCategory() {
    return category;
  }

  public void setCategory(Integer category) {
    this.category = category;
  }

  public Station priceCategory(Integer priceCategory) {
    this.priceCategory = priceCategory;
    return this;
  }

   /**
   * determines in some respect the price for train stops at a specific station (1..7)
   * @return priceCategory
  **/
  @ApiModelProperty(value = "determines in some respect the price for train stops at a specific station (1..7)")
  public Integer getPriceCategory() {
    return priceCategory;
  }

  public void setPriceCategory(Integer priceCategory) {
    this.priceCategory = priceCategory;
  }

  public Station federalState(String federalState) {
    this.federalState = federalState;
    return this;
  }

   /**
   * german federal state
   * @return federalState
  **/
  @ApiModelProperty(value = "german federal state")
  public String getFederalState() {
    return federalState;
  }

  public void setFederalState(String federalState) {
    this.federalState = federalState;
  }

  public Station hasParking(Boolean hasParking) {
    this.hasParking = hasParking;
    return this;
  }

   /**
   * public parking y/n
   * @return hasParking
  **/
  @ApiModelProperty(value = "public parking y/n")
  public Boolean isHasParking() {
    return hasParking;
  }

  public void setHasParking(Boolean hasParking) {
    this.hasParking = hasParking;
  }

  public Station hasBicycleParking(Boolean hasBicycleParking) {
    this.hasBicycleParking = hasBicycleParking;
    return this;
  }

   /**
   * public bicycle parking y/n
   * @return hasBicycleParking
  **/
  @ApiModelProperty(value = "public bicycle parking y/n")
  public Boolean isHasBicycleParking() {
    return hasBicycleParking;
  }

  public void setHasBicycleParking(Boolean hasBicycleParking) {
    this.hasBicycleParking = hasBicycleParking;
  }

  public Station hasPublicFacilities(Boolean hasPublicFacilities) {
    this.hasPublicFacilities = hasPublicFacilities;
    return this;
  }

   /**
   * public facilities y/n
   * @return hasPublicFacilities
  **/
  @ApiModelProperty(value = "public facilities y/n")
  public Boolean isHasPublicFacilities() {
    return hasPublicFacilities;
  }

  public void setHasPublicFacilities(Boolean hasPublicFacilities) {
    this.hasPublicFacilities = hasPublicFacilities;
  }

  public Station hasLockerSystem(Boolean hasLockerSystem) {
    this.hasLockerSystem = hasLockerSystem;
    return this;
  }

   /**
   * public facilities y/n
   * @return hasLockerSystem
  **/
  @ApiModelProperty(value = "public facilities y/n")
  public Boolean isHasLockerSystem() {
    return hasLockerSystem;
  }

  public void setHasLockerSystem(Boolean hasLockerSystem) {
    this.hasLockerSystem = hasLockerSystem;
  }

  public Station hasLocalPublicTransport(Boolean hasLocalPublicTransport) {
    this.hasLocalPublicTransport = hasLocalPublicTransport;
    return this;
  }

   /**
   * local public transport y/n
   * @return hasLocalPublicTransport
  **/
  @ApiModelProperty(value = "local public transport y/n")
  public Boolean isHasLocalPublicTransport() {
    return hasLocalPublicTransport;
  }

  public void setHasLocalPublicTransport(Boolean hasLocalPublicTransport) {
    this.hasLocalPublicTransport = hasLocalPublicTransport;
  }

  public Station hasTaxiRank(Boolean hasTaxiRank) {
    this.hasTaxiRank = hasTaxiRank;
    return this;
  }

   /**
   * taxi rank in front of the station y/n
   * @return hasTaxiRank
  **/
  @ApiModelProperty(value = "taxi rank in front of the station y/n")
  public Boolean isHasTaxiRank() {
    return hasTaxiRank;
  }

  public void setHasTaxiRank(Boolean hasTaxiRank) {
    this.hasTaxiRank = hasTaxiRank;
  }

  public Station hasTravelNecessities(Boolean hasTravelNecessities) {
    this.hasTravelNecessities = hasTravelNecessities;
    return this;
  }

   /**
   * a shop for travel necessities y/n
   * @return hasTravelNecessities
  **/
  @ApiModelProperty(value = "a shop for travel necessities y/n")
  public Boolean isHasTravelNecessities() {
    return hasTravelNecessities;
  }

  public void setHasTravelNecessities(Boolean hasTravelNecessities) {
    this.hasTravelNecessities = hasTravelNecessities;
  }

  public Station hasSteplessAccess(Partial hasSteplessAccess) {
    this.hasSteplessAccess = hasSteplessAccess;
    return this;
  }

   /**
   * stepless access is availiable yes, no or partial
   * @return hasSteplessAccess
  **/
  @ApiModelProperty(value = "stepless access is availiable yes, no or partial")
  public Partial getHasSteplessAccess() {
    return hasSteplessAccess;
  }

  public void setHasSteplessAccess(Partial hasSteplessAccess) {
    this.hasSteplessAccess = hasSteplessAccess;
  }

  public Station hasMobilityService(String hasMobilityService) {
    this.hasMobilityService = hasMobilityService;
    return this;
  }

   /**
   * values are &#39;no&#39;, &#39;yes, advance notification is requested...&#39; or &#39;yes, advance notification is required...&#39;
   * @return hasMobilityService
  **/
  @ApiModelProperty(value = "values are 'no', 'yes, advance notification is requested...' or 'yes, advance notification is required...'")
  public String getHasMobilityService() {
    return hasMobilityService;
  }

  public void setHasMobilityService(String hasMobilityService) {
    this.hasMobilityService = hasMobilityService;
  }

  public Station hasWiFi(Boolean hasWiFi) {
    this.hasWiFi = hasWiFi;
    return this;
  }

   /**
   * public Wi-Fi is available y/n
   * @return hasWiFi
  **/
  @ApiModelProperty(value = "public Wi-Fi is available y/n")
  public Boolean isHasWiFi() {
    return hasWiFi;
  }

  public void setHasWiFi(Boolean hasWiFi) {
    this.hasWiFi = hasWiFi;
  }

  public Station hasTravelCenter(Boolean hasTravelCenter) {
    this.hasTravelCenter = hasTravelCenter;
    return this;
  }

   /**
   * local travel center y/n
   * @return hasTravelCenter
  **/
  @ApiModelProperty(value = "local travel center y/n")
  public Boolean isHasTravelCenter() {
    return hasTravelCenter;
  }

  public void setHasTravelCenter(Boolean hasTravelCenter) {
    this.hasTravelCenter = hasTravelCenter;
  }

  public Station hasRailwayMission(Boolean hasRailwayMission) {
    this.hasRailwayMission = hasRailwayMission;
    return this;
  }

   /**
   * railway mission y/n
   * @return hasRailwayMission
  **/
  @ApiModelProperty(value = "railway mission y/n")
  public Boolean isHasRailwayMission() {
    return hasRailwayMission;
  }

  public void setHasRailwayMission(Boolean hasRailwayMission) {
    this.hasRailwayMission = hasRailwayMission;
  }

  public Station hasDBLounge(Boolean hasDBLounge) {
    this.hasDBLounge = hasDBLounge;
    return this;
  }

   /**
   * DB lounge y/n
   * @return hasDBLounge
  **/
  @ApiModelProperty(value = "DB lounge y/n")
  public Boolean isHasDBLounge() {
    return hasDBLounge;
  }

  public void setHasDBLounge(Boolean hasDBLounge) {
    this.hasDBLounge = hasDBLounge;
  }

  public Station hasLostAndFound(Boolean hasLostAndFound) {
    this.hasLostAndFound = hasLostAndFound;
    return this;
  }

   /**
   * lost and found y/n
   * @return hasLostAndFound
  **/
  @ApiModelProperty(value = "lost and found y/n")
  public Boolean isHasLostAndFound() {
    return hasLostAndFound;
  }

  public void setHasLostAndFound(Boolean hasLostAndFound) {
    this.hasLostAndFound = hasLostAndFound;
  }

  public Station hasCarRental(Boolean hasCarRental) {
    this.hasCarRental = hasCarRental;
    return this;
  }

   /**
   * car sharing or car rental y/n
   * @return hasCarRental
  **/
  @ApiModelProperty(value = "car sharing or car rental y/n")
  public Boolean isHasCarRental() {
    return hasCarRental;
  }

  public void setHasCarRental(Boolean hasCarRental) {
    this.hasCarRental = hasCarRental;
  }

  public Station evaNumbers(List<EVANumber> evaNumbers) {
    this.evaNumbers = evaNumbers;
    return this;
  }

  public Station addEvaNumbersItem(EVANumber evaNumbersItem) {
    if (this.evaNumbers == null) {
      this.evaNumbers = new ArrayList<EVANumber>();
    }
    this.evaNumbers.add(evaNumbersItem);
    return this;
  }

   /**
   * station related EVA-Numbers
   * @return evaNumbers
  **/
  @ApiModelProperty(value = "station related EVA-Numbers")
  public List<EVANumber> getEvaNumbers() {
    return evaNumbers;
  }

  public void setEvaNumbers(List<EVANumber> evaNumbers) {
    this.evaNumbers = evaNumbers;
  }

  public Station riL100Identifiers(List<RiL100Identifier> riL100Identifiers) {
    this.ril100Identifiers = riL100Identifiers;
    return this;
  }

  public Station addRiL100IdentifiersItem(RiL100Identifier riL100IdentifiersItem) {
    if (this.ril100Identifiers == null) {
      this.ril100Identifiers = new ArrayList<RiL100Identifier>();
    }
    this.ril100Identifiers.add(riL100IdentifiersItem);
    return this;
  }

   /**
   * station related Ril100s
   * @return ril100Identifiers
  **/
  @ApiModelProperty(value = "station related Ril100s")
  public List<RiL100Identifier> getRil100Identifiers() {
    return ril100Identifiers;
  }

  public void setRil100Identifiers(List<RiL100Identifier> riL100Identifiers) {
    this.ril100Identifiers = riL100Identifiers;
  }

  public Station timetableOffice(TimetableOffice timetableOffice) {
    this.timetableOffice = timetableOffice;
    return this;
  }

   /**
   * Get timetableOffice
   * @return timetableOffice
  **/
  @ApiModelProperty(value = "")
  public TimetableOffice getTimetableOffice() {
    return timetableOffice;
  }

  public void setTimetableOffice(TimetableOffice timetableOffice) {
    this.timetableOffice = timetableOffice;
  }

  public Station stationManagement(StationManagementRef stationManagement) {
    this.stationManagement = stationManagement;
    return this;
  }

   /**
   * Get stationManagement
   * @return stationManagement
  **/
  @ApiModelProperty(value = "")
  public StationManagementRef getStationManagement() {
    return stationManagement;
  }

  public void setStationManagement(StationManagementRef stationManagement) {
    this.stationManagement = stationManagement;
  }

  public Station localServiceStaff(Schedule localServiceStaff) {
    this.localServiceStaff = localServiceStaff;
    return this;
  }

   /**
   * Get localServiceStaff
   * @return localServiceStaff
  **/
  @ApiModelProperty(value = "")
  public Schedule getLocalServiceStaff() {
    return localServiceStaff;
  }

  public void setLocalServiceStaff(Schedule localServiceStaff) {
    this.localServiceStaff = localServiceStaff;
  }

  public Station dbinformation(Schedule dbinformation) {
    this.dbinformation = dbinformation;
    return this;
  }

   /**
   * Get dbinformation
   * @return dbinformation
  **/
  @ApiModelProperty(value = "")
  public Schedule getDbinformation() {
    return dbinformation;
  }

  public void setDbinformation(Schedule dbinformation) {
    this.dbinformation = dbinformation;
  }

  public Station regionalbereich(RegionalBereichRef regionalbereich) {
    this.regionalbereich = regionalbereich;
    return this;
  }

   /**
   * Get regionalbereich
   * @return regionalbereich
  **/
  @ApiModelProperty(value = "")
  public RegionalBereichRef getRegionalbereich() {
    return regionalbereich;
  }

  public void setRegionalbereich(RegionalBereichRef regionalbereich) {
    this.regionalbereich = regionalbereich;
  }

  public Station szentrale(SZentraleRef szentrale) {
    this.szentrale = szentrale;
    return this;
  }

   /**
   * Get szentrale
   * @return szentrale
  **/
  @ApiModelProperty(value = "")
  public SZentraleRef getSzentrale() {
    return szentrale;
  }

  public void setSzentrale(SZentraleRef szentrale) {
    this.szentrale = szentrale;
  }

  public Station aufgabentraeger(Aufgabentraeger aufgabentraeger) {
    this.aufgabentraeger = aufgabentraeger;
    return this;
  }

   /**
   * Get aufgabentraeger
   * @return aufgabentraeger
  **/
  @ApiModelProperty(value = "")
  public Aufgabentraeger getAufgabentraeger() {
    return aufgabentraeger;
  }

  public void setAufgabentraeger(Aufgabentraeger aufgabentraeger) {
    this.aufgabentraeger = aufgabentraeger;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Station station = (Station) o;
    return Objects.equals(this.number, station.number) &&
        Objects.equals(this.name, station.name) &&
        Objects.equals(this.mailingAddress, station.mailingAddress) &&
        Objects.equals(this.category, station.category) &&
        Objects.equals(this.priceCategory, station.priceCategory) &&
        Objects.equals(this.federalState, station.federalState) &&
        Objects.equals(this.hasParking, station.hasParking) &&
        Objects.equals(this.hasBicycleParking, station.hasBicycleParking) &&
        Objects.equals(this.hasPublicFacilities, station.hasPublicFacilities) &&
        Objects.equals(this.hasLockerSystem, station.hasLockerSystem) &&
        Objects.equals(this.hasLocalPublicTransport, station.hasLocalPublicTransport) &&
        Objects.equals(this.hasTaxiRank, station.hasTaxiRank) &&
        Objects.equals(this.hasTravelNecessities, station.hasTravelNecessities) &&
        Objects.equals(this.hasSteplessAccess, station.hasSteplessAccess) &&
        Objects.equals(this.hasMobilityService, station.hasMobilityService) &&
        Objects.equals(this.hasWiFi, station.hasWiFi) &&
        Objects.equals(this.hasTravelCenter, station.hasTravelCenter) &&
        Objects.equals(this.hasRailwayMission, station.hasRailwayMission) &&
        Objects.equals(this.hasDBLounge, station.hasDBLounge) &&
        Objects.equals(this.hasLostAndFound, station.hasLostAndFound) &&
        Objects.equals(this.hasCarRental, station.hasCarRental) &&
        Objects.equals(this.evaNumbers, station.evaNumbers) &&
        Objects.equals(this.ril100Identifiers, station.ril100Identifiers) &&
        Objects.equals(this.timetableOffice, station.timetableOffice) &&
        Objects.equals(this.stationManagement, station.stationManagement) &&
        Objects.equals(this.localServiceStaff, station.localServiceStaff) &&
        Objects.equals(this.dbinformation, station.dbinformation) &&
        Objects.equals(this.regionalbereich, station.regionalbereich) &&
        Objects.equals(this.szentrale, station.szentrale) &&
        Objects.equals(this.aufgabentraeger, station.aufgabentraeger);
  }

  @Override
  public int hashCode() {
    return Objects.hash(number, name, mailingAddress, category, priceCategory, federalState, hasParking, hasBicycleParking, hasPublicFacilities, hasLockerSystem, hasLocalPublicTransport, hasTaxiRank, hasTravelNecessities, hasSteplessAccess, hasMobilityService, hasWiFi, hasTravelCenter, hasRailwayMission, hasDBLounge, hasLostAndFound, hasCarRental, evaNumbers, ril100Identifiers, timetableOffice, stationManagement, localServiceStaff, dbinformation, regionalbereich, szentrale, aufgabentraeger);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Station {\n");
    
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    mailingAddress: ").append(toIndentedString(mailingAddress)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    priceCategory: ").append(toIndentedString(priceCategory)).append("\n");
    sb.append("    federalState: ").append(toIndentedString(federalState)).append("\n");
    sb.append("    hasParking: ").append(toIndentedString(hasParking)).append("\n");
    sb.append("    hasBicycleParking: ").append(toIndentedString(hasBicycleParking)).append("\n");
    sb.append("    hasPublicFacilities: ").append(toIndentedString(hasPublicFacilities)).append("\n");
    sb.append("    hasLockerSystem: ").append(toIndentedString(hasLockerSystem)).append("\n");
    sb.append("    hasLocalPublicTransport: ").append(toIndentedString(hasLocalPublicTransport)).append("\n");
    sb.append("    hasTaxiRank: ").append(toIndentedString(hasTaxiRank)).append("\n");
    sb.append("    hasTravelNecessities: ").append(toIndentedString(hasTravelNecessities)).append("\n");
    sb.append("    hasSteplessAccess: ").append(toIndentedString(hasSteplessAccess)).append("\n");
    sb.append("    hasMobilityService: ").append(toIndentedString(hasMobilityService)).append("\n");
    sb.append("    hasWiFi: ").append(toIndentedString(hasWiFi)).append("\n");
    sb.append("    hasTravelCenter: ").append(toIndentedString(hasTravelCenter)).append("\n");
    sb.append("    hasRailwayMission: ").append(toIndentedString(hasRailwayMission)).append("\n");
    sb.append("    hasDBLounge: ").append(toIndentedString(hasDBLounge)).append("\n");
    sb.append("    hasLostAndFound: ").append(toIndentedString(hasLostAndFound)).append("\n");
    sb.append("    hasCarRental: ").append(toIndentedString(hasCarRental)).append("\n");
    sb.append("    evaNumbers: ").append(toIndentedString(evaNumbers)).append("\n");
    sb.append("    ril100Identifiers: ").append(toIndentedString(ril100Identifiers)).append("\n");
    sb.append("    timetableOffice: ").append(toIndentedString(timetableOffice)).append("\n");
    sb.append("    stationManagement: ").append(toIndentedString(stationManagement)).append("\n");
    sb.append("    localServiceStaff: ").append(toIndentedString(localServiceStaff)).append("\n");
    sb.append("    dbinformation: ").append(toIndentedString(dbinformation)).append("\n");
    sb.append("    regionalbereich: ").append(toIndentedString(regionalbereich)).append("\n");
    sb.append("    szentrale: ").append(toIndentedString(szentrale)).append("\n");
    sb.append("    aufgabentraeger: ").append(toIndentedString(aufgabentraeger)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

